/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'activeBills' : bigint,
  'deliveredBills' : bigint,
  'totalBills' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'date' : string,
  'customerMobile' : string,
  'grandTotal' : number,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'productName' : string,
  'price' : number,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null };
export interface Prescription {
  'id' : bigint,
  'customerName' : string,
  'date' : string,
  'customerMobile' : string,
  'notes' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'stock' : bigint,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface RegisteredUser {
  'principal' : string,
  'name' : string,
  'role' : string,
}
export interface _SERVICE {
  'getAllRegisteredUsers' : ActorMethod<[], Array<RegisteredUser>>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrder' : ActorMethod<
    [string, string, Array<OrderItem>, number, string],
    bigint
  >,
  'addPrescription' : ActorMethod<[string, string, string, string], bigint>,
  'addProduct' : ActorMethod<[string, number, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deletePrescription' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeliveredOrders' : ActorMethod<[], Array<Order>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPendingOrders' : ActorMethod<[], Array<Order>>,
  'getPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, string, number, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];